In [11]:
"""Python tutorial to illustrate pointwise multiplication, pointwise
addition, shifting, convolution, and slicing of NumPy arrays.

Written to accompany lectures for a module called:
CS356 Image and optical processing
Thomas J. Naughton, Maynooth University Department of Computer Science
Created: tjn, CS, MU, 15 X 2014
Last updated: tjn, CS, MU, 4 XI 2020

How to run
----------

This file is not meant to be run in its entirety. There are intentional
run-time errors for example, showing the "out of bounds" behaviour of
NumPy indexing. Instead, each line is intended to be run separately, or where
an assignment statement stretches over multiple lines, it is intended
that you would run all of these lines together.
"""

# This line below is required to be run initially
from numpy import array, arange, roll, convolve

In [12]:
# The = operator means assignment
f = array([1, 2, 1, 2, 1, 3, 5, 6, 7, 1, 3])
h = array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])
hr = h[::-1]  # Reverse the list
print(f)
print(f*h)
print(f*hr)

[1 2 1 2 1 3 5 6 7 1 3]
[0 0 0 0 0 0 5 6 7 0 0]
[0 0 1 2 1 0 0 0 0 0 0]


In [13]:
f = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
g = array([0, 0, 0, 1, 1, 1, 0, 0, 0])
f
g
print(f+g)
print(f-g)

[1 2 3 5 6 7 7 8 9]
[1 2 3 3 4 5 7 8 9]


In [14]:
h = arange(6)
print(h)
print(roll(h, 1))
print(roll(h, -3))

[0 1 2 3 4 5]
[5 0 1 2 3 4]
[3 4 5 0 1 2]


In [15]:
# Looking at the graphical examples of "convolution" in Wikipedia will
# be sufficient to understand this concept.
print(convolve([1, 2, 3], [0, 1, 0]))

[0 1 2 3 0]


In [16]:
print(convolve([3, 4, 7, 2, 1, 5], [2, 2, 1]))

[ 6 14 25 22 13 14 11  5]


In [17]:
print(convolve([0, 0, 1, 1, 0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0, 1, 1, 0, 0]))

[0 0 0 0 1 2 1 0 2 4 2 0 1 2 1 0 0 0 0]


In [18]:
# This is a classic convolution example. You should make sure to
# understand this input-output pair.
k = array([0, 0, 1, 0, 1, 0, 0])
print(convolve(k, k))

[0 0 0 0 1 0 2 0 1 0 0 0 0]


In [19]:
# An important technique for manipulating arrays follows: slicing.
# First, basic indexing of an array
a = array([10, 20, 30, 40, 50])
print(a)
print('First element:', a[0])  # First element
print('Third element:', a[2])
print('Length:', len(a))

[10 20 30 40 50]
First element: 10
Third element: 30
Length: 5


In [20]:
print(a[len(a)])  # Out of bounds error because a list of length 5 only has valid indices 0..4

IndexError: index 5 is out of bounds for axis 0 with size 5

In [21]:
print(a[len(a)-1])  # Last element
print(a[-1])  # Shorthand for above (-1 means the last element, -2 means the second last, etc.)

50
50


In [22]:
# Next, slicing
print(a[0:2])  # A slice using two array indices
print(a[:2])  # A slice using two array indices
print(a[2:len(a)])  # A slice using two array indices
print(a[2:])  # Shorthand for above

[10 20]
[10 20]
[30 40 50]
[30 40 50]


In [23]:
print(a[2:len(a)-1])  # A slice using two array indices
print(a[2:-1])  # Shorthand for above

print(a[2:len(a)-2])  # A slice using two array indices
print(a[2:-2])  # Shorthand for above

print((a[1:-1])[1:-1])  # A slice of a slice
print(a[1:-1][1:-1])  # We can drop the parentheses

[30 40]
[30 40]
[30]
[30]
[30]
[30]


In [24]:
# Each of these is equivalent
print(a)
print(a[0:len(a)])
print(a[0:])
print(a[:len(a)])
print(a[:])

[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]


In [25]:
# A third parameter can be used in a slice definition
print(a[::1])  # All elements
print(a[::2])  # All elements with even indices
print(a[::-1])  # All elements in reverse order

[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [26]:
# Slicing in two dimensions
data = array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
    [4, 5, 6]])

print(data, '\n')
print('a value:', data[1, 2], '\n')
print('a row:', data[0, :], '\n')  # One particular row
print('a column:', data[:, 0], '\n')  # One particular column
print('all but first row:\n', data[1:, :], '\n')  # Include all but the first row
print('all but first column:\n', data[:, :-1])  # Include all but the last column

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]] 

a value: 3 

a row: [1 2 3] 

a column: [1 1 1 4] 

all but first row:
 [[1 2 3]
 [1 2 3]
 [4 5 6]] 

all but first column:
 [[1 2]
 [1 2]
 [1 2]
 [4 5]]


In [27]:
# Indexing a slice based on a condition
a = array([10, 20, 30, 40, 50, 30])
print(a)
# The == operator tests for equality and returns a boolean
print(a == 30)

[10 20 30 40 50 30]
[False False  True False False  True]


In [28]:
# Replace values based on a condition
a[a == 30] = 99  # Just an assignment, so nothing returned and nothing to print
print(a)
print((a % 20) == 0)  # The modulus operator
a[(a % 20) == 0] = 0  # Just an assignment, so nothing returned and nothing to print
print(a)

[10 20 99 40 50 99]
[False  True False  True False False]
[10  0 99  0 50 99]


In [29]:
# Let's look at an example of this in two dimensions
data = array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
    [4, 5, 6]])

print(data, '\n')

data[data[:, 2] == 3, 1] = 99
print(data)

# If you understand the assignment statement above, then you have
# successfully completed the tutorial. If not, please investigate its
# behaviour by changing the values in that line of code until you do.

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]] 

[[ 1 99  3]
 [ 1 99  3]
 [ 1 99  3]
 [ 4  5  6]]
